# Generated by Django 4.0 on 2024-10-22 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='programme',
            unique_together={('name', 'abb', 'department'), ('name', 'abb')},
        ),
        migrations.AddField(
            model_name='programme',
            name='duration',
            field=models.PositiveIntegerField(choices=[('1', 'One Year'), ('2', 'Two Years'), ('3', 'Three Years'), ('4', 'Four Years'), ('5', 'Five Years')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='middle_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AlterUniqueTogether(
            name='programme',
            unique_together={('name', 'abb', 'department'), ('name', 'abb'), ('duration', 'name', 'abb')},
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_of_study', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('continuing', 'Continuing'), ('finalist', 'finalist'), ('associate', 'associate')], default='continuing', max_length=12)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='student_prog', to='registration.programme')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_programme', to='registration.user')),
            ],
            options={
                'db_table': 'student',
                'unique_together': {('programme', 'user')},
            },
        ),
    ]
