# Generated by Django 4.0 on 2024-10-26 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_semister_remove_year_only one year to be current_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('semester 1', 'semester 1'), ('semester 2', 'semester 2')], max_length=40)),
                ('is_current', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.year')),
            ],
            options={
                'db_table': 'semester',
            },
        ),
        migrations.DeleteModel(
            name='Semister',
        ),
        migrations.AddConstraint(
            model_name='semester',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('is_current',), name='only one semester can be current'),
        ),
    ]
