# Generated by Django 4.0 on 2024-10-26 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_semester_delete_semister_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bill',
            },
        ),
        migrations.CreateModel(
            name='StudentBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('unpaid', 'unpaid'), ('partial paid', 'partial paid'), ('full paid', 'full paid')], default='unpaid', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'student_bill',
            },
        ),
        migrations.CreateModel(
            name='StudentBillPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'student_bill_payment',
            },
        ),
        migrations.RemoveConstraint(
            model_name='semester',
            name='only one semester can be current',
        ),
        migrations.AddField(
            model_name='studentbillpayment',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.user'),
        ),
        migrations.AddField(
            model_name='studentbillpayment',
            name='student_bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.studentbill'),
        ),
        migrations.AddField(
            model_name='studentbill',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.bill'),
        ),
        migrations.AddField(
            model_name='studentbill',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.semester'),
        ),
        migrations.AddField(
            model_name='studentbill',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.student'),
        ),
        migrations.AlterUniqueTogether(
            name='studentbill',
            unique_together={('student', 'bill', 'semester')},
        ),
    ]
