# Generated by Django 4.0 on 2024-10-26 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_bill_studentbill_studentbillpayment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentbillpayment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.user'),
        ),
    ]
