# Generated by Django 4.0 on 2024-10-26 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_alter_studentbillpayment_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='semester',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='registration.semester'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='studentbill',
            unique_together={('student', 'bill')},
        ),
        migrations.RemoveField(
            model_name='studentbill',
            name='semester',
        ),
    ]
