# Generated by Django 4.0 on 2024-10-26 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_bill_semester_alter_studentbill_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bill',
            unique_together={('semester', 'name')},
        ),
    ]
