# Generated by Django 4.0 on 2024-10-26 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0012_alter_bill_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'account',
            },
        ),
        migrations.AlterField(
            model_name='studentbill',
            name='status',
            field=models.CharField(choices=[('unpaid', 'unpaid'), ('partial payment', 'partial payment'), ('paid', 'paid')], default='unpaid', max_length=20),
        ),
    ]
