# Generated by Django 4.0 on 2024-10-26 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0013_account_alter_studentbill_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentbill',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentbillpayment',
            name='method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Mobile', 'Mobile'), ('Bank', 'Bank')], default='Cash', max_length=10),
        ),
    ]
