# Generated by Django 4.0 on 2024-10-27 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0014_studentbill_paid_amount_studentbillpayment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentbill',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
