# Generated by Django 4.0 on 2024-10-29 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0016_event_eventcommittee_eventcollection_eventbill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='end_date',
            new_name='event_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='event',
            name='committee_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount to be paid by committee'),
        ),
        migrations.AlterField(
            model_name='event',
            name='member_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount to be paid by member'),
        ),
        migrations.AlterField(
            model_name='event',
            name='projection',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Target amount'),
        ),
    ]
