# Generated by Django 4.0 on 2024-10-29 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0017_rename_end_date_event_event_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventcollection',
            options={'ordering': ['event_bill'], 'verbose_name': 'Event Collection', 'verbose_name_plural': 'Event Collections'},
        ),
        migrations.RemoveField(
            model_name='event',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='eventcollection',
            name='event',
        ),
        migrations.AddField(
            model_name='eventbill',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='eventcollection',
            name='event_bill',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='registration.eventbill'),
            preserve_default=False,
        ),
    ]
