# Generated by Django 4.0 on 2024-10-29 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0018_alter_eventcollection_options_remove_event_semester_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventbill',
            name='status',
            field=models.CharField(choices=[('unpaid', 'unpaid'), ('partial payment', 'partial payment'), ('paid', 'paid')], default='unpaid', max_length=20),
        ),
    ]
