# Generated by Django 4.0 on 2024-10-29 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0020_eventcollection_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventbill',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterUniqueTogether(
            name='eventbill',
            unique_together={('event', 'student')},
        ),
    ]
