# Generated by Django 4.0 on 2024-10-29 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0021_alter_eventbill_amount_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventcommittee',
            unique_together={('event', 'position', 'student')},
        ),
    ]
