# Generated by Django 4.0 on 2024-10-29 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0022_alter_eventcommittee_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventcommittee',
            unique_together={('event', 'position', 'student'), ('event', 'student')},
        ),
    ]
