# Generated by Django 4.0 on 2024-10-29 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0023_alter_eventcommittee_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventcollection',
            old_name='collected_amount',
            new_name='paid_amount',
        ),
    ]
