# Generated by Django 4.0 on 2024-10-29 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0024_rename_collected_amount_eventcollection_paid_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventcollection',
            name='projection',
        ),
    ]
